name: 'release'

on:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    strategy:
      fail-fast: false

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - uses: SebRollen/toml-action@v1.0.1
        id: version
        with:
          file: 'src-tauri/Cargo.toml'
          field: 'package.version'
      - run: echo ${{steps.version.outputs.value}}
      - name: setup rust
        uses: dtolnay/rust-toolchain@stable
      - name: setup tauri cli
        run: cargo install tauri-cli
      - name: setup pnpm deps
        run: pnpm i
      - name: compile
        run: cargo tauri build
        env:
          CURSES_TWITCH_CLIENT_ID: ${{secrets.CURSES_TWITCH_CLIENT_ID}}

      - name: create release
        uses: softprops/action-gh-release@v1
#        if: ${{startsWith(github.ref, 'refs/tags/') }}
        with:
          name: Release ${{steps.version.outputs.value}}
          tag_name: v${{steps.version.outputs.value}}
          draft: true
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            src-tauri/target/release/curses.exe
            src-tauri/target/release/bundle/msi/curses_${{steps.version.outputs.value}}_x64_en-US.msi
